[package]
name = "rts_lab_flight"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
amiquip = "0.4.2"
serde = "1.0.201"
serde_json = "1.0.117"
